version: "3.9"

services:
  auth-service:
    build: .
    container_name: auth_service
    command: poetry run uvicorn lib.controllers.auth_controller:router --host 0.0.0.0 --port 8080
    environment:
      DATABASE_URL: postgresql://user:pass@db:5432/authdb
      JWT_SECRET_KEY: supersecretkey
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: auth_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: authdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
